/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-01-17 12:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Objects;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import com.foodDelivaryApp.model.User;
import com.foodDelivaryApp.model.Order;
import com.foodDelivaryApp.model.CartItem;
import com.foodDelivaryApp.servlets.UserServlet;
import com.foodDelivaryApp.model.Cart;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.ArrayList;

public final class ordernow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("com.foodDelivaryApp.model.Order");
    _jspx_imports_classes.add("com.foodDelivaryApp.model.CartItem");
    _jspx_imports_classes.add("javax.servlet.ServletException");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletResponse");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("com.foodDelivaryApp.model.Cart");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.Objects");
    _jspx_imports_classes.add("com.foodDelivaryApp.model.User");
    _jspx_imports_classes.add("com.foodDelivaryApp.servlets.UserServlet");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
	Order order = (Order) request.getAttribute("order");
	User user = (User)session.getAttribute("user");
	
	System.out.print(isLoggedIn);
	System.out.print(user);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Order Now</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/OrderNow.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header> \r\n");
      out.write("    		<div id=\"logo\">Food<span id=\"logo-s\">Go</span></div>\r\n");
      out.write("            ");
 String username = (String) session.getAttribute("username"); 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
 if (!(username==null) && !username.isEmpty()) { 
      out.write("\r\n");
      out.write("               <div id=\"logo-1\">Welcome  \r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath() );
      out.write("/UserServlet?action=logout\"><span id=\"logo-s-1\">");
      out.print( username );
      out.write("</span></a></div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <span class=\"sign\"><a class=\"act\" href=\"signUp.jsp\">SIGN UP</a></span>\r\n");
      out.write("                <span class=\"sign\"><a class=\"act\" href=\"login.jsp\">LOG IN</a></span>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <span class=\"sign\"><a class=\"act\" href=\"checkout.jsp\">View Cart</a></span>\r\n");
      out.write("	</header>\r\n");
      out.write("<h1>Order Now</h1>\r\n");
      out.write("\r\n");
      out.write("<form id=\"orderForm\" action=\"");
      out.print( request.getContextPath() + "/orderConfirmationServlet" );
      out.write("\" method=\"POST\">\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <input type=\"hidden\" name=\"restaurantId\" value=\"");
      out.print( order.getRestaurentid() );
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2 id=\"h2\">Total Amount</h2>\r\n");
      out.write("        <p class=\"total-amount\">Total Amount:  &#x20B9; ");
      out.print( order.getTotalamount() );
      out.write("</p>\r\n");
      out.write("        <input type=\"hidden\" id=\"amount\" name=\"totalAmount\" value=");
      out.print(order.getTotalamount() );
      out.write(">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Delivery Address</h2>\r\n");
      out.write("        <label for=\"address\">Address:</label>\r\n");
      out.write("        <input type=\"text\" id=\"address\" name=\"address\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Payment Method</h2>\r\n");
      out.write("        <label for=\"paymentMethod\">Payment Method:</label>\r\n");
      out.write("        <select id=\"paymentMethod\" name=\"paymentMethod\" required>\r\n");
      out.write("            <option value=\"UPI\">UPI</option>\r\n");
      out.write("            <option value=\"Cash\">Cash</option>\r\n");
      out.write("            <option value=\"Debit Card\">Debit Card</option>\r\n");
      out.write("            <option value=\"Credit Card\">Credit Card</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("	<div class=\"button-container\">\r\n");
      out.write("    	<button onclick=\"proceedToOrder()\"> Proceed to Order </button>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("    function proceedToOrder() {\r\n");
      out.write("        var url = '");
      out.print( isLoggedIn != null && isLoggedIn ? request.getContextPath() + "/orderConfirmationServlet" : request.getContextPath() + "/errorpage2.jsp" );
      out.write("';\r\n");
      out.write("        window.location.href = url;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
